// All site content lives here. Edit this file to update the portfolio.

window.SITE = {
  name: "Lucky Rathee",
  role: "AI Engineer",
  location: "Bahadurgarh, Haryana, India",
  email: "lucky.dev2311@gmail.com",
  phone: "+91 7988452163",
  github: "https://github.com/LuckyRathee",
  linkedin: "https://www.linkedin.com/in/lucky-rathee",
  resume: "assets/Lucky-Rathee-Resume.pdf",
};

window.PROJECTS = [
  {
    id: "b2b-prospecting-engine",
    tree: [
      ["", "<k>website-outreach-engine/</k>"],
      ["", "├── <k>.ai/</k>                 <c>context · tasks · changelog</c>"],
      ["", "├── <k>api/</k>                 <c>main · auth · scraper_api · state</c>"],
      ["", "├── <k>scrapers/</k>            <c>google_maps_scraper.py</c>"],
      ["", "├── <k>tools/</k>               <c>25 pipeline modules</c>"],
      ["", "│   ├── pipeline_orchestrator.py"],
      ["", "│   ├── hermes_ai_client.py"],
      ["", "│   ├── qualifier.py"],
      ["", "│   ├── ai_demo_director.py"],
      ["", "│   ├── demo_generator.py · demo_qa.py"],
      ["", "│   ├── deployer.py"],
      ["", "│   ├── outreach_writer.py · outreach_approval.py"],
      ["", "│   ├── email_dispatcher.py · whatsapp_dispatcher.py"],
      ["", "│   └── crm_manager.py · followup_manager.py"],
      ["", "├── <k>workflows/</k>           <c>8 agent workflows</c>"],
      ["", "├── <k>skills/</k>              <c>Hermes skill files</c>"],
      ["", "├── <k>clients/&lt;lead_id&gt;/</k>   <c>design · website · outreach · QA</c>"],
      ["", "├── <k>frontend/</k>            <c>React + Vite dashboard</c>"],
      ["", "├── <k>lead-engine-mobile/</k>  <c>mobile companion app</c>"],
      ["", "├── <k>tests/</k>               <c>13 test suites</c>"],
      ["", "├── <k>docs/</k>                <c>14 design docs</c>"],
      ["", "├── .github/workflows/ci.yml"],
      ["", "└── AGENTS.md"],
    ],
    facts: [["Pipeline modules", "25"], ["Test suites", "13"], ["Agent workflows", "8"]],
    access: "Internal system · walkthrough on request",
    title: "Autonomous B2B Prospecting & Agentic Web Engine",
    short: "Agentic Web Engine",
    category: "Agentic AI",
    year: "Sep 2026",
    stack: ["Python", "Playwright", "Hermes Agent", "LLM Orchestration", "TDD", "Vercel MCP", "Tailscale", "React", "Vite", "Tailwind", "GitHub Actions"],
    summary:
      "An AI outreach engine built on Hermes Agent with a 27-skill design system — it scrapes and qualifies leads, then generates demo websites from real business data.",
    metric: "27-skill agent",
    replaces: "Manual prospecting",
    highlights: [
      "Built an AI outreach engine using Hermes Agent with a 27-skill design system for automated lead scraping, qualification, and LLM-powered demo website generation with real business data.",
      "Engineered automated pipelines for CRM state tracking, follow-up scheduling, deployment validation via Vercel MCP, and outreach-readiness reporting with audit trails.",
      "Deployed the full-stack system with optimized builds, CORS-configured HTTPS endpoints via Tailscale Funnel, 15+ REST API endpoints, and support for 4 concurrent users.",
      "Runs end to end as a pipeline of 25 modules: Google Maps scraping, contact enrichment, deduplication, qualification, AI demo direction and generation, automated demo QA, deployment, then email and WhatsApp outreach behind an approval step.",
      "Backed by 13 test suites, 14 design documents and GitHub Actions CI, with a React + Vite dashboard and a mobile companion app for tracking leads.",
    ],
    code: [
      ["c", "# hermes · outreach pipeline"],
      ["", "leads = <k>scrape</k>(region, niche)"],
      ["", "for lead in <k>qualify</k>(leads):"],
      ["", "    site = <k>agent</k>.build_demo(lead)"],
      ["", "    <k>vercel_mcp</k>.deploy(site)"],
      ["", "    crm.advance(lead, <k>\"ready\"</k>)"],
    ],
  },
  {
    id: "ultron-v1",
    access: "Private repository · demo on request",
    title: "ULTRON v1 — Agentic OS & Desktop Automation",
    short: "ULTRON v1",
    category: "Multi-Agent Systems",
    year: "Jul 2026",
    stack: ["Python", "MCP", "Multi-Agent Systems", "Speech-to-Text"],
    summary:
      "A voice-operated, plugin-based agentic framework that delegates work down a hierarchy of sub-agents and drives the desktop at the OS level.",
    metric: "Voice → Action",
    replaces: "Clicks & context switching",
    highlights: [
      "Architected a voice-operated, plugin-based agentic framework featuring hierarchical multi-agent delegation, dynamically spawning sub-agents to execute multi-step tasks.",
      "Integrated Model Context Protocol (MCP) clients and plugin modules to standardize runtime tool discovery, context ingestion, and dynamic skill execution across frontier LLMs.",
      "Engineered local desktop actuation pipelines, enabling deterministic OS-level automation, process control, and system tasks via low-latency speech parsing.",
    ],
    code: [
      ["c", "# ultron · voice loop"],
      ["", "cmd = <k>stt</k>.listen()"],
      ["", "plan = orchestrator.<k>plan</k>(cmd)"],
      ["", "for task in plan.steps:"],
      ["", "    agent = <k>spawn</k>(task.skill)"],
      ["", "    agent.run(tools=<k>mcp</k>.discover())"],
    ],
  },
  {
    id: "mehfil",
    demo: "https://mehfil-app-ten.vercel.app/",
    images: [
      ["Stations", "assets/mehfil-home.jpg", "Mehfil station picker with six themed live broadcasts"],
      ["On air", "assets/mehfil-station.jpg", "Mehfil's Theth Desi station playing live, with listener count and waveform"],
      ["Mobile", "assets/mehfil-mobile.jpg", "Mehfil on a phone", "tall"],
    ],
    team: "Built with Harshit Saharan (AWS & backend infra) and Pankaj (audio SDK & performance). I led AI orchestration and LLM-assisted architecture.",
    title: "Mehfil — Ambient Cultural Audio-Visual Platform",
    short: "Mehfil",
    category: "Realtime Web · Team project",
    year: "2026",
    stack: ["React", "Vite", "Supabase Realtime", "Spotify Web Playback SDK", "Framer Motion", "AWS", "Vercel"],
    summary:
      "Synchronized streaming radio with six themed stations: everyone tuned in hears the same track at the exact same second.",
    metric: "Live sync",
    replaces: "Refresh to catch up",
    highlights: [
      "Developed a low-latency web application leveraging the Spotify Web Playback SDK and Framer Motion for interactive, synchronized media streaming.",
      "Configured Supabase Realtime for live cross-client synchronization, managing distributed audio-visual state and ensuring fluid UI transitions.",
      "Led AI orchestration and LLM-assisted architecture in a three-person team, alongside backend/AWS and audio-SDK specialists.",
    ],
    code: [
      ["c", "// mehfil · shared room state"],
      ["", "supabase.<k>channel</k>('room')"],
      ["", "  .on('broadcast', syncPlayback)"],
      ["", "  .<k>subscribe</k>()"],
      ["", "player.<k>seek</k>(state.position_ms)"],
    ],
  },
  {
    id: "self-hosted-n8n",
    access: "Client infrastructure · on-demand EC2",
    title: "Self-Hosted n8n Automation Infrastructure",
    short: "n8n Infrastructure",
    category: "Cloud & DevOps",
    year: "2026",
    stack: ["n8n", "Docker Compose", "Google Cloud Run", "AWS EC2", "Caddy"],
    summary:
      "Self-hosted n8n automation pipelines for freelance clients, deployed on Google Cloud Run and AWS EC2 behind a Caddy reverse proxy with custom domains.",
    metric: "Self-hosted",
    replaces: "SaaS limits",
    highlights: [
      "Architected self-hosted n8n automation pipelines on Google Cloud Run and AWS EC2 via Docker Compose.",
      "Configured a Caddy reverse proxy for automatic HTTPS and custom domain routing.",
      "Runs on an on-demand EC2 instance that is started only when workflows need to run, keeping hosting costs near zero when idle.",
      "Engineered an automated lead dispatch system with Google Sheets and Apps Script, orchestrating quota distribution and real-time manager synchronization.",
    ],
    code: [
      ["c", "# docker-compose.yml"],
      ["", "services:"],
      ["", "  <k>n8n</k>:"],
      ["", "    image: n8nio/n8n"],
      ["", "  <k>caddy</k>:"],
      ["", "    ports: [\"443:443\"]"],
    ],
  },
  {
    id: "telegram-ops-assistant",
    access: "Private workflow · demo on request",
    title: "Telegram Voice Ops Assistant",
    short: "Voice Ops Assistant",
    category: "Automation",
    year: "2026",
    stack: ["n8n", "Telegram Bot API", "LLMs", "Speech-to-Text"],
    summary:
      "A Telegram-based voice assistant for freelancer operations — task management, communication and admin work, handled by talking to it.",
    metric: "Voice ops",
    replaces: "Admin busywork",
    highlights: [
      "Designed and deployed a Telegram-based freelancer ops voice assistant using n8n.",
      "Streamlined task management, communication, and administrative tasks through voice commands.",
    ],
    code: [
      ["c", "# telegram → n8n → action"],
      ["", "on <k>voice_message</k>:"],
      ["", "  text = transcribe(audio)"],
      ["", "  intent = <k>llm</k>.classify(text)"],
      ["", "  route(intent) → tasks | mail | notes"],
    ],
  },
];

window.RESEARCH = [
  {
    id: "stai-2026",
    category: "Research",
    venue: "STAI 2026",
    date: "2026",
    status: "Accepted",
    title: "Architectural Design of 6G-Based Ultra-Low-Latency Communication for Remote Medical Services",
    summary:
      "A 6G architecture for mission-critical remote healthcare that combines edge AI, network slicing and lightweight security, reaching 0.38 ms average end-to-end latency in simulation.",
    keywords: ["6G", "Ultra-low latency", "Remote healthcare", "Edge computing", "Network slicing", "Terahertz", "Reinforcement learning"],
    abstract: [
      "Telemedicine, real-time patient monitoring and robot-assisted remote surgery need networks with ultra-low latency, ultra-high reliability and massive connectivity. That is beyond what today's 5G networks can deliver.",
      "This paper designs a 6G-based ultra-low-latency communication architecture for mission-critical remote healthcare. It combines terahertz communication and intelligent reflecting surfaces with edge computing, distributed AI and network slicing to cut end-to-end latency, raise reliability and adapt quality of service to each stream of medical data.",
      "It analyzes latency, packet loss, reliability and energy efficiency across remote-healthcare scenarios, and addresses the security and privacy of ultra-fast medical data with AI-based trust management and lightweight cryptography.",
    ],
    pipeline: [
      ["Medical data sources", "Wearables, implants, imaging, surgical robots"],
      ["6G access network", "Terahertz links + intelligent reflecting surfaces"],
      ["Edge computing node", "Distributed at base stations & hospital gateways"],
      ["Latency critical?", "Yes → edge AI · No → cloud", "decision"],
      ["AI network orchestration", "RL controllers + per-service network slices"],
      ["Secure transmission", "Lightweight crypto, edge intrusion detection, blockchain logs"],
      ["Remote healthcare app", "Telesurgery, emergency care, monitoring"],
    ],
    metrics: [
      ["0.38", "ms", "Average end-to-end latency"],
      ["99.9997", "%", "Network reliability at 1,000 devices"],
      ["18.4", "Gbps", "Throughput over terahertz (+42%)"],
      ["29", "%", "Lower total energy use"],
      ["54", "%", "Less cloud offloading"],
      ["3.6", "%", "Security overhead (vs 10–12%)"],
    ],
    latency: [
      ["Proposed 6G", 0.38],
      ["5G-URLLC", 1.2],
      ["Conventional edge", 2.6],
    ],
    equations: [
      ["End-to-end latency", "L<sub>total</sub> = L<sub>tx</sub> + L<sub>prop</sub> + L<sub>edge</sub> + L<sub>queue</sub>"],
      ["Network reliability", "R<sub>net</sub> = ∏<sub>i=1..N</sub> (1 − P<sub>i</sub>)"],
      ["Edge processing time", "T<sub>edge</sub> = D / C<sub>edge</sub>"],
      ["Energy consumption", "E<sub>total</sub> = P<sub>tx</sub>·T<sub>tx</sub> + P<sub>edge</sub>·T<sub>edge</sub>"],
    ],
    body: [
      "Critical services such as remote surgery and emergency care stayed below 0.5 ms end to end, meeting the sub-millisecond requirement for real-time care. Packet delivery stayed above 99.999% even at peak traffic.",
      "AI-driven network slicing cut packet loss by 31% and improved spectrum efficiency by 27%. Edge AI inference averaged 0.21 ms, fast enough for real-time clinical decisions.",
      "The results come from simulation of a multi-edge network with mixed medical traffic. Real-world deployment of terahertz links and reflecting surfaces, mobility handovers and the trade-off between lightweight security and strength remain open challenges.",
    ],
  },
];
